## Reshape

In [3]:
import numpy as np

1.

In [4]:
D1 = D2 = D3 = D4 = 2
A = np.random.rand(D1, D2, D3, D4)

In [6]:
A = np.transpose(A, [0,2, 1, 3])
A.reshape(D1*D3, D2*D4)

array([[0.32884596, 0.93459693, 0.9687344 , 0.612741  ],
       [0.63527703, 0.06615419, 0.33211365, 0.12342139],
       [0.99253896, 0.9165508 , 0.1140045 , 0.72852139],
       [0.08854874, 0.66482121, 0.16388116, 0.5844726 ]])

2.

In [8]:
D1 = D2 = D3 = 2
B = np.random.rand(D1, D2, D3)

In [16]:
B = np.transpose(B, [0, 2, 1])
B.reshape(D1 * D3, D2)

array([[0.66023353, 0.59603786],
       [0.36008511, 0.2668324 ],
       [0.16378576, 0.95417771],
       [0.84577097, 0.12665249]])

3.

In [14]:
D1 = D2 = D3 = D4 = D5 = 2
C = np.random.rand(D1, D2, D3, D4, D5)

In [15]:
C = np.transpose(C, [2, 0, 1, 3, 4])
C.reshape(D3, -1)

array([[0.75057121, 0.07594682, 0.15261276, 0.65185471, 0.57145238,
        0.60533756, 0.94746407, 0.82655946, 0.13842051, 0.39291105,
        0.31984383, 0.93698396, 0.48565565, 0.75059048, 0.69136686,
        0.34135214],
       [0.08455775, 0.30690146, 0.10287382, 0.85206659, 0.33609219,
        0.40957564, 0.890199  , 0.50734882, 0.99719271, 0.92195225,
        0.90900728, 0.56510423, 0.160924  , 0.40983632, 0.7594736 ,
        0.09691981]])