In [7]:
import numpy as np

Di=3
Dj=3
Dk=4

A = np.arange(Di*Dj*Dk).reshape(Di, Dj, Dk) # A_ijk

In [13]:
A.shape

(3, 3, 4)

In [8]:
A

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]])

In [14]:
A_reshaped = np.reshape(A, [Di*Dj, Dk]) # A_xk

In [15]:
A_reshaped

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35]])

In [17]:
A_reshaped.shape

(9, 4)

In [18]:
# Split indices to return to orginial tensor:
np.reshape(A_reshaped, [Di, Dj, Dk])

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]])